@host=https://localhost:7195
@hostId=bcda7109-c2e0-476e-8c9a-6c48ddd62a64

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlci5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6Ik1hdGlqYSIsImZhbWlseV9uYW1lIjoixIxhdmxvdmnEhyIsImp0aSI6IjkyMDkwYWM2LTRmNWYtNDdmMC05MDViLTk2NjU4ZmUwYzk5MSIsImV4cCI6MTY3MzgwNTIwOCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.Zo73HZvIRSPD4wgmAhSTx5zh4LS5vQ9Zp432EaW2cVc

{
    "name":"Good Menu",
    "description":"Something good",
    "sections":[
        {
            "name":"Fortisch",
            "description":"Something before",
            "items":[
                {
                    "name":"Brod",
                    "description":"A brod"
                }
            ]
        },
        {
            "name":"Haubttisch",
            "description":"Main course",
            "items":[
                {
                    "name":"Vegetable soup",
                    "description":"Nice soup"
                },
                 {
                    "name":"Seitan",
                    "description":"Not satan"
                }
            ]
        },
        {
            "name":"Nachtisch",
            "description":"Desert",
            "items":[
                {
                    "name":"Apple",
                    "description":"An apple"
                }
            ]
        }
    ]
}