@host=https://localhost:7195

GET  {{host}}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNjg4MGNkNS1kMjNiLTRmODItOTMxZi1hYmQ1NzJlMmFkMTkiLCJnaXZlbl9uYW1lIjoiTWF0aWphIiwiZmFtaWx5X25hbWUiOiLEjGF2bG92acSHIiwianRpIjoiOGRkMzc2MWYtMWQzZC00NzhjLThhMzktZWI1ZmYyMjllNjI5IiwiZXhwIjoxNjczNjc2NDYyLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.KH4kazmKlnTyhNl3PHJoSOUiHoRZnUTWF4nT3uhW9FI